<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\State;
class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { 
        $model = new State;
       
        $model::truncate();
        $insertdata = [[
            'state' => "Alabama",
            'short_name' => "AL",
            'region' => "South",
            'relativity' => "0.922",
            'tax' => 6,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 2,
            'service_fee' => '',
            'service_fee_type' => 1,
            'stamping_fee' => '',
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 2,
            'inspection_fee' => 0,
            'multi_inspection_fee' => 0,
            'surplusline_notices' => '<p>&nbsp;</p><h1><strong>IMPORTANT NOTICE</strong></h1><hr /><h2>&nbsp;</h2><h2><strong>ALABAMA SURPLUS LINES DISCLOSURE NOTICE</strong></h2><p>&nbsp;</p><h2><strong>This contract is registered and delivered as a surplus line coverage under the Alabama Surplus Line Insurance Law.</strong></h2><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><hr />',
      ] ,
       [ 'state' => "Alaska",
            'short_name' => "AK",
            'region' => "West",
            'relativity' => "0.923",
            'tax' =>2.7,
            'is_enabled' => 1,
            'filing_fee' => 1,
            'filing_fee_type' => 1,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 0,
            'multi_inspection_fee' => 0,
            'surplusline_notices' =>'<p>COVINGTON SPECIALTY INSURANCE COMPANY</p><p>&nbsp;</p><h1><strong>IMPORTANT NOTICE</strong></h1><hr /><p>&nbsp;</p><h2><strong>ALASKA SURPLUS LINES DISCLOSURE NOTICE</strong></h2><h3>&nbsp;</h3><h3>This is evidence of insurance procured and developed under the Alaska Surplus Lines Law, AS 21.34. It is not covered by the Alaska Insurance Guaranty Association Act, AS 21.80.</h3><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><hr /><p>RSG 99067 0106</p>',
     ],
		[
            'state' => "Arizona",
            'short_name' => "AZ",
            'region' => "West",
            'relativity' => "1.34",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .2,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' =>'<ol><li><h3>The surplus lines policy or evidence of&nbsp;coverage is issued by a surplus lines insurer that&nbsp;is not a domestic surplus lines insurer:&nbsp;Pursuant to section 20-401.01, subsection B, paragraph 1,&nbsp;Arizona Revised Statutes, this policy is issued by&nbsp;an insurer that does not possess a certificate of&nbsp;authority from the director of the Arizona&nbsp;Department of Insurance. If the insurer that issued this policy becomes insolvent, insureds or&nbsp;claimants will not be eligible for insurance&nbsp;guaranty fund protection pursuant to title 20,&nbsp;Arizona Revised Statutes.</h3>	</li>	<li>	<h3>The surplus lines policy or evidence of&nbsp;coverage is issued by a domestic surplus lines&nbsp;insurer:&nbsp;if the insurer that issued this policy&nbsp;becomes insolvent, insureds or claimants will not&nbsp;be eligible for insurance guaranty fund protection pursuant to title 20, Arizona Revised Statutes.</h3>	</li></ol><p>&nbsp;</p>',
        ],
        [
            'state' => "Arkansas",
            'short_name' => "AR",
            'region' => "South",
            'relativity' => "1.368",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],


        [
            'state' => "California",
            'short_name' => "CA",
            'region' => "West",
            'relativity' => "1.412",
            'tax' => 3.0,
            'is_enabled' => 1,
            'filing_fee' =>'',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .20,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "<p>In the event of our failure to pay any amount claimed to be due, we, at your request, will submit to the jurisdiction of any court of competent jurisdiction within the United States of America. Nothing in this condition constitutes or should be understood to constitute a waiver of our rights to commence an action in any Court of competent jurisdiction in the United States, to remove an action to a United States District Court or seek a transfer of a case to another Court as permitted by the laws of the United States or of any state in the United States, moreover, this endorsement is not an agreement that the law of a particular jurisdiction applies to any dispute under the policy.</p><p>Service of process in such suit may be made upon Corporation Service Company, 2710 Gateway Oaks Drive, Suite 150N, Sacramento, California 95833-3505. In any suit instituted against it upon this contract, we will abide by the final decision of such Court or of any Appellate Court in the event of an appeal.</p><p>The above named is authorized and directed to accept service of process on our behalf in any such suit and/or upon your request to give a written undertaking to you that we will enter a general appearance upon our behalf in the event such a suit shall be instituted.</p><p>Further, pursuant to any statute of any state, territory or district of the United States of America, which makes provision therefore, we hereby designate the Superintendent, Commissioner or Director of Insurance or other officer specified for the purpose in the statute, or his successor or successors in office, as our true and lawful attorney upon whom may be served any lawful process in any action, suit or proceeding instituted by you or on your behalf or any beneficiary hereunder arising out of this contract of insurance, and we hereby designate the above named as the person to whom the above named is authorized to mail such process or a true copy thereof.</p>",
        ],


        [
            'state' => "Colorado",
            'short_name' => "CO",
            'region' => "West",
            'relativity' => "0.966",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],
		[
            'state' => "Connecticut",
            'short_name' => "CT",
            'region' => "Northeast",
            'relativity' => "1.013",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' => '',
            'surplusline_notices' => "",
        ],

       [
            'state' => "Delaware",
            'short_name' => "DE",
            'region' => "South",
            'relativity' => "0.808",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],
        [
            'state' => "Florida",
            'short_name' => "FL",
            'region' => "South",
            'relativity' => "0.94",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => .1,
            'service_fee_type' => 1,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],
		[
            'state' => "Georgia",
            'short_name' => "GA",
            'region' => "South",
            'relativity' => "1.071",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],
		[
            'state' => "Hawaii",
            'short_name' => "HI",
            'region' => "West",
            'relativity' => "0.557",
            'tax' => 4.68,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],
		[
            'state' => "Idaho",
            'short_name' => "ID",
            'region' => "West",
            'relativity' => "0.794",
            'tax' => 1.5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .5,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "",
        ],

   [
            'state' => "Illinois",
            'short_name' => "IL",
            'region' => "Midwest",
            'relativity' => "0.858",
            'tax' => 3.5,
            'is_enabled' => 1,
            'filing_fee' => .2,
            'filing_fee_type' => 1,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .125,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => '',
            'multi_inspection_fee' =>'',
            'surplusline_notices' => "<p>The insurer hereby designates the Director of the Illinois Department of Insurance and his successor or successors in office, as its true and lawful attorney upon whom may be served any lawful process in any action, suit or proceeding instituted by or on behalf of the insured or any beneficiary hereunder arising out of this contract of insurance.</p>",
        ],

    [
            'state' => "Indiana",
            'short_name' => "IN",
            'region' => "Midwest",
            'relativity' => "1.034",
            'tax' => 2.5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
         [
            'state' => "Iowa",
            'short_name' => "IA",
            'region' => "Midwest",
            'relativity' => "0.942",
            'tax' => 1,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Kansas",
            'short_name' => "KS",
            'region' => "Midwest",
            'relativity' => "0.935",
            'tax' => 6,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' =>'',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Kentucky",
            'short_name' => "KY",
            'region' => "South",
            'relativity' => "1.117",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => 1.8,
            'transaction_fee_type' => 1,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Louisiana",
            'short_name' => "LA",
            'region' => "South",
            'relativity' => "0.877",
            'tax' => 4.85,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Maine",
            'short_name' => "ME",
            'region' => "Northeast",
            'relativity' => "1.005",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Maryland",
            'short_name' => "MD",
            'region' => "South",
            'relativity' => "0.855",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Massachusetts",
            'short_name' => "MA",
            'region' => "Northeast",
            'relativity' => "1.387",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Michigan",
            'short_name' => "MI",
            'region' => "Midwest",
            'relativity' => "0.719",
            'tax' => 2.5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Minnesota",
            'short_name' => "MN",
            'region' => "Midwest",
            'relativity' => "0.759",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .04,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

  [
            'state' => "Mississippi",
            'short_name' => "MS",
            'region' => "South",
            'relativity' => "0.716",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .25,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Missouri",
            'short_name' => "MO",
            'region' => "Midwest",
            'relativity' => "0.953",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Montana",
            'short_name' => "MT",
            'region' => "West",
            'relativity' => "0.74",
            'tax' => 2.75,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .25,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Nebraska",
            'short_name' => "NE",
            'region' => "Midwest",
            'relativity' => "0.956",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Nevada",
            'short_name' => "NV",
            'region' => "West",
            'relativity' => "0.647",
            'tax' => 3.5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .4,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "New Hampshire",
            'short_name' => "NH",
            'region' => "Northeast",
            'relativity' => "0.735",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "New Jersey",
            'short_name' => "NJ",
            'region' => "Northeast",
            'relativity' => "1.166",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "New Mexico",
            'short_name' => "NM",
            'region' => "West",
            'relativity' => "1.384",
            'tax' => 3.003,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "New York",
            'short_name' => "NY",
            'region' => "Northeast",
            'relativity' => "1.532",
            'tax' => 3.6,
            'is_enabled' => 1,
            'filing_fee' =>'',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .17,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "North Carolina",
            'short_name' => "NC",
            'region' => "South",
            'relativity' => "1.684",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "North Dakota",
            'short_name' => "ND",
            'region' => "Midwest",
            'relativity' => "0.908",
            'tax' => 1.75,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Ohio",
            'short_name' => "OH",
            'region' => "Midwest",
            'relativity' => "0.766",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Oklahoma",
            'short_name' => "OK",
            'region' => "South",
            'relativity' => "1.011",
            'tax' => 6,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

   [
            'state' => "Oregon",
            'short_name' => "OR",
            'region' => "West",
            'relativity' => "1.299",
            'tax' => 2.3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => 15,
            'stamping_fee_type' => 2,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Pennsylvania",
            'short_name' => "PA",
            'region' => "Northeast",
            'relativity' => "1.18",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => 20,
            'stamping_fee_type' => 2,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Rhode Island",
            'short_name' => "RI",
            'region' => "Northeast",
            'relativity' => "0.783",
            'tax' => 4,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "South Carolina",
            'short_name' => "SC",
            'region' => "South",
            'relativity' => "0.562",
            'tax' => 6,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "South Dakota",
            'short_name' => "SD",
            'region' => "Midwest",
            'relativity' => "0.34",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "Tennessee",
            'short_name' => "TN",
            'region' => "South",
            'relativity' => "1.341",
            'tax' => 5,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "Texas",
            'short_name' => "TX",
            'region' => "South",
            'relativity' => "1.636",
            'tax' =>  4.85,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .15,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => '<p>It is agreed that, as an eligible surplus lines insurance company in the State of Texas, Covington Specialty Insurance Company (CSIC], accepts the irrevocable appointment of the Secretary of State as binding on CSIC and its successors in interest, to be the lawful attorney for the service of CSIC. The Secretary of State may be served with any process, notice, or demand arising out of doing insurance business in Texas by CSIC, except in an action, suit, or proceeding by the State Board of Insured or by the State of Texas. CSIC further agrees that legal process served in the above manner shall have the same legal force and validity as personal service of process in Texas on CSIC or its successor in interest</p><p>In the event service is tendered to the Secretary of State, service of process in such suit may be made by the Commissioner upon the Senior Claims Officer of RSUI Group, Inc., 945 East Paces Ferry Rd., Atlanta, GA 30326-1160 or his designee.</p><p><img src="https://egolombis.com/cms/assets/img/Capture1.PNG" style="border-bottom:1px solid black" /></p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Phillip McCrorie, President<br />&nbsp; &nbsp;&nbsp;Covington Specialty Insurance Company</p>',
        ],

   [
            'state' => "Utah",
            'short_name' => "UT",
            'region' => "West",
            'relativity' => "0.752",
            'tax' => 4.25,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .18,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Vermont",
            'short_name' => "VT",
            'region' => "Northeast",
            'relativity' => "0.879",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],

    [
            'state' => "Virginia",
            'short_name' => "VA",
            'region' => "South",
            'relativity' => "0.654",
            'tax' => 2.25,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
		    'state' => "Washington",
            'short_name' => "WA",
            'region' => "West",
            'relativity' => "1.066",
            'tax' => 2,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => .10,
            'stamping_fee_type' => 1,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "West Virginia",
            'short_name' => "WV",
            'region' => "South",
            'relativity' => "0.8",
            'tax' => 4.55,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [   'state' => "Wisconsin",
            'short_name' => "WI",
            'region' => "Midwest",
            'relativity' => "2.207",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 0,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' => '',
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ],
        [
            'state' => "Wyoming",
            'short_name' => "WY",
            'region' => "West",
            'relativity' => "0.844",
            'tax' => 3,
            'is_enabled' => 1,
            'filing_fee' => '',
            'filing_fee_type' => 1,
            'service_fee' => '',
            'service_fee_type' => 0,
            'stamping_fee' => '',
            'stamping_fee_type' => 0,
            'transaction_fee' =>'' ,
            'transaction_fee_type' => 0,
            'inspection_fee' => 95,
            'multi_inspection_fee' => 45,
            'surplusline_notices' => "",
        ]
		];
         foreach($insertdata as $insert){
          $model::create($insert);
       }

    }
}
